- include_vars: "../defaults/{{ cluster }}/{{ location }}.yaml"

- name: git update
  import_tasks: git.yaml

- name: build jito sol
  import_tasks: build.yaml

- name: key management
  import_tasks: key_management.yaml

- name: render files
  import_tasks: files.yaml

- name: snapshot download
  include_tasks: snapshot_downloader.yaml
  when: download_snapshot|default(true)|bool == true

- name: restart without waiting
  become: true
  become_user: root
  shell: /home/solana/restart.sh 1
  when: download_snapshot|default(true)|bool == true

- name: restart with waiting
  become: true
  become_user: root
  shell: /home/solana/restart.sh
  when: download_snapshot|default(true)|bool == false
